spring:
  profiles:
    active: local
  application:
    name: security-demo-01
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9000/auth/realms/security-demo
        registration:
          keycloak:
            client-id: app-client
#            client-secret: <你的secret>   # public client 可不填
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/auth/realms/security-demo
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2.server.resource: TRACE

