spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/security_db
    username: postgres
    password: postgres
  application:
    name: security-demo-01
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9000/auth/realms/security-demo
        registration:
          keycloak:
            client-id: app-client
#            client-secret: <你的secret>   # public client 可不填
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/auth/realms/security-demo
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.security.demo.auth.mapper
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2.server.resource: TRACE

